### ISSUE TITLE
500 error on trying to delete program

### ISSUE THREAD

**Issue by htysc** [csse-uoft/SNM-I#105]
```
TypeError: type.getCascadePaths is not a function or its return value is not iterable
    at Function.getCascadePaths (/home/[...]/snm-i/SNM-I/backend/node_modules/graphdb-utils/build/graphDBModel.js:99:46)
    at Function.findOneAndDelete (/home/[...]/snm-i/SNM-I/backend/node_modules/graphdb-utils/build/graphDBModel.js:648:32)
    at Function.findByIdAndDelete (/home/[...]/snm-i/SNM-I/backend/node_modules/graphdb-utils/build/graphDBModel.js:667:21)
    at deleteSingleGenericHelper (/home/[...]/snm-i/SNM-I/backend/services/genericData/index.js:669:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deleteSingleGeneric (/home/[...]/snm-i/SNM-I/backend/services/genericData/index.js:676:5)
DELETE /api/generic/program/1 500 25.818 ms - 875
```

**Comment by LesterLyu** [comment]
This is a bug in `graphdb-utils`.
